name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build React App
      run: npm run build

    - name: Install Capacitor Android
      run: |
        npm install @capacitor/android
        npx cap add android

    - name: Sync Capacitor project
      run: npx cap sync android

    - name: Build debug APK
      run: cd android && ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: tpneo-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
